<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Afghanistan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Albania</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Algeria</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">American Samoa</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Andorra</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Angola</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Anguilla</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Antigua &amp; Barbuda</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Argentina</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Armenia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Aruba</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Australia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Austria</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Azerbaijan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bahamas</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bahrain</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bangladesh</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Barbados</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Belarus</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Belgium</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Belize</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Benin</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bermuda</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bhutan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bolivia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bonaire</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bosnia &amp; Herzegovina</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Botswana</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Brazil</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">British Indian Ocean Ter</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Brunei</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Bulgaria</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Burkina Faso</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Burundi</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cambodia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cameroon</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Canada</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Canary Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cape Verde</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cayman Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Central African Republic</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Chad</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Channel Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Chile</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">China</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Christmas Island</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cocos Island</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Colombia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Comoros</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Congo</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cook Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Costa Rica</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cote D'Ivoire</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Croatia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cuba</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Curacao</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Cyprus</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Czech Republic</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Denmark</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Djibouti</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Dominica</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Dominican Republic</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">East Timor</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Ecuador</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Egypt</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">El Salvador</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Equatorial Guinea</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Eritrea</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Estonia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Ethiopia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Falkland Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Faroe Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Fiji</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Finland</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">France</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">French Guiana</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">French Polynesia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">French Southern Ter</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Gabon</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Gambia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Georgia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Germany</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Ghana</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Gibraltar</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Great Britain</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Greece</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Greenland</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Grenada</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Guadeloupe</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Guam</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Guatemala</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Guinea</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Guyana</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Haiti</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Hawaii</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Honduras</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Hong Kong</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Hungary</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Iceland</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">India</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Indonesia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Iran</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Iraq</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Ireland</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Isle of Man</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Israel</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Italy</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Jamaica</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Japan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Jordan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Kazakhstan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Kenya</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Kiribati</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Korea North</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Korea South</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Kuwait</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Kyrgyzstan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Laos</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Latvia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Lebanon</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Lesotho</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Liberia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Libya</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Liechtenstein</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Lithuania</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Luxembourg</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Macau</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Macedonia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Madagascar</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Malaysia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Malawi</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Maldives</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Mali</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Malta</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Marshall Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Martinique</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Mauritania</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Mauritius</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Mayotte</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Mexico</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Midway Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Moldova</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Monaco</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Mongolia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Montserrat</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Morocco</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Mozambique</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Myanmar</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Nambia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Nauru</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Nepal</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Netherland Antilles</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Netherlands (Holland, Europe)</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Nevis</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">New Caledonia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">New Zealand</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Nicaragua</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Niger</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Nigeria</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Niue</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Norfolk Island</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Norway</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Oman</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Pakistan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Palau Island</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Palestine</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Panama</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Papua New Guinea</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Paraguay</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Peru</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Philippines</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Pitcairn Island</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Poland</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Portugal</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Puerto Rico</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Qatar</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Republic of Montenegro</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Republic of Serbia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Reunion</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Romania</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Russia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Rwanda</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Barthelemy</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Eustatius</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Helena</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Kitts-Nevis</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Lucia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Maarten</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Pierre &amp; Miquelon</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">St Vincent &amp; Grenadines</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Saipan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Samoa</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Samoa American</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">San Marino</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Sao Tome &amp; Principe</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Saudi Arabia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Senegal</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Serbia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Seychelles</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Sierra Leone</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Singapore</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Slovakia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Slovenia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Solomon Islands</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Somalia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">South Africa</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Spain</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Sri Lanka</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Sudan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Suriname</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Swaziland</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Sweden</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Switzerland</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Syria</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Tahiti</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Taiwan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Tajikistan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Tanzania</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Thailand</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Togo</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Tokelau</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Tonga</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Trinidad &amp; Tobago</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Tunisia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Turkey</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Turkmenistan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Turks &amp; Caicos Is</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Tuvalu</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Uganda</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Ukraine</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">United Arab Emirates</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">United Kingdom</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">United States of America</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Uruguay</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Uzbekistan</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Vanuatu</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Vatican City State</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Venezuela</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Vietnam</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Virgin Islands (Brit)</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Virgin Islands (USA)</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Wake Island</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Wallis &amp; Futana Is</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Yemen</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Zaire</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Zambia</option>
<option value="<?php echo $managed_pricing['0']['subregion_price'] ?>">Zimbabwe</option>